Sb 31 upgrade reward function
Heecatee/Swarmball pull request #34
Opened 2020-06-03 16:22 UTC by Ichtiostega

2020-06-04 12:53 UTC, TheMoira approved these changes

2020-06-05 11:29 UTC, PatrykRadon approved these changes

2020-06-06 11:53 UTC, Heecatee approved these changes

2020-06-06 11:53 UTC, PatrykRadon commented on environment/swarmball_env.py
> +        observations = {'picture': self.sim.space_near_goal_object(), 'thresholds': self.sim.threshold_positions()}
```suggestion
        observations = {'picture': self.sim.space_near_goal_object(), 'thresholds': self.sim.threshold_positions() - self.sim._goal_object.body.position[0]}
```

2020-06-06 11:56 UTC, PatrykRadon requested changes
zwracane miały być pozycje thresholdów względem pozycji obiektu, ponieważ obraz jest zcentrowany na obiekcie i pozycje thresholdów dobrze jakby miały jakiś związek z wejściem jakim jest obraz  mapy

2020-06-07 11:16 UTC, Grzybu1 requested changes

2020-06-07 11:16 UTC, Grzybu1 commented on environment/swarmball_env.py
> +        return {'picture': self.sim.space_near_goal_object(), 'thresholds': self.sim.threshold_positions()}
Tutaj tak samo jak Patryk zasugerował

2020-06-13 16:52 UTC, Heecatee approved these changes

2020-06-14 14:55 UTC, PatrykRadon approved these changes

2020-06-14 17:04 UTC, Grzybu1 approved these changes

2020-06-14 17:04 UTC, merged